/***********************************************************************************
 *
 * @@@ Simple money transaction system using CORBA - java - IDL file definition
 *  
 *  @ Class Account
 *          * Balance
 *          * Deposit cash()
 *          * Withdraw cash()
 *  
 *  @ Class AccountManagement
 *          * Account check()
 **********************************************************************************/


module SMTS
{
    interface Account
    {
        readonly attribute double balance;
        exception InsufficientBalance{};
        double deposit(in double amount);
        double withdraw(in double sum) raises (InsufficientBalance);
    };
    
    interface AccountManagement
    {
        exception invalidAccount{};
        Account accountCheck(in long accid ) raises (invalidAccount);
    };
    
};