/***********************************************************************************
 *
 * @@@ Simple money transaction system using CORBA - java - IDL file definition
 *  
 *  @ Method -> Account
 *          * Account ID
 *          * Balance
 *          * Set account ID()
 *          * Set balance()
 *  
 **********************************************************************************/


module SMTS
{
    interface Account
    {
        attribute string accountID;
        attribute double balance;
        
        void setAccountID(inout string accid);
        void setBalance(inout double value);
    };
    
};